### ISSUE TITLE
Summary 

### ISSUE THREAD

**Issue by siyuan126** [gsunbq/pwp-capstones#1]
Overall Score: 13/16
Overall great job! Here is the breakdown.

Criteria 1: Valid Python Code
Score Level: 3 (meets expectation)
Comment(s): Code included runs without errors. Good job adding checkpoint after each function, it makes both debug and code review much easier! For function ngram_generator, the output is not entirely correct, please check the code. 

Criteria 2: Implementation of Project Requirements
Score Level: 3 (meets expectations)
Comment(s): Code produces the suite of functions and classes required of it and calls them in an appropriate order.

Criteria 3: Software Architecture
Score Level: 4 (Exceeds expectations)
Comment(s): Code is separated into distinct classes and functions which are invoked for their own purposes.

Criteria 4: Uses Python Language Features
Score Level: 3 (Meets expectations)
Comment(s): Code uses language features appropriately. Please use triple quotes around multi line text (See PEP8).

**Comment by gsunbq** [comment]
I don't know what I'm meant to do, @siyuan126 . Am I OK having closed the issue?
